

POST http://localhost:3000/scraping
Content-Type: application/json

{
    "titulo": "Nuestro segundo articulo",
    "imagen": "http:/primer_articulo",
    "descripcion": "Nuestro primer articulo descripción",
    "enlace": "http:/segundo_articulo"
}

###

DELETE http://localhost:3000/scraping/2


###

GET http://localhost:3000/scraping/10

###

PUT http://localhost:3000/scraping/5
Content-Type: application/json

{
    "titulo": "Nuestro segundo articulo editado",
    "imagen": "http:/primer_articulo",
    "descripcion": "Nuestro primer articulo descripción",
    "enlace": "http:/primer_articulo"
}
